# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: C++

on:

  pull_request:
    branches:
    - master
    - 'envoy-release/**'
    - 'istio-release/**'

  push:
    branches:
    - master
    - 'envoy-release/**'
    - 'istio-release/**'

jobs:

  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Format (clang-format)
      run: |
        sudo apt-get install clang-format-9
        find . -name "*.h" -o -name "*.cc" -o -name "*.proto" | grep -v ".pb." | xargs -n1 clang-format-9 -i
        git diff --exit-code

    - name: Format (buildifier)
      run: |
        go get -u github.com/bazelbuild/buildtools/buildifier
        export PATH=$PATH:$(go env GOPATH)/bin
        find . -name "BUILD" | xargs -n1 buildifier -mode=check

    - name: Format (addlicense)
      run: |
        go get -u github.com/google/addlicense
        export PATH=$PATH:$(go env GOPATH)/bin
        addlicense -check .

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO(mathetake): Add other runtimes.
        runtime: [ "wasmtime" ]

    steps:
    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel-${{ matrix.runtime }}

    - name: Test
      run: |
        bazel test --define runtime=${{ matrix.runtime }} //...

    - name: Test (signed Wasm module)
      # Hex-encoded public key (signature_key1.pub):
      # xxd -p -c 256 test/test_data/signature_key1.pub | cut -b9-
      run: |
        bazel test --define runtime=${{ matrix.runtime }} --cxxopt=-DPROXY_WASM_VERIFY_WITH_ED25519_PUBKEY=\"33fbfb5d412d33b165ab252ccd8ed5cd01c7d41faaf7e38e1e7d267380fbc72c\" //test:signature_util_test
